DP_COUNT			equ WM_USER+1 	; wParam = count 
DP_INIT				equ WM_USER+2 	; wParam = count / lParam = maxi
DP_TEXT				equ WM_USER+3 	; wParam = text 
DP_FONT				equ WM_USER+4 	; wParam = Font
DP_COLORBKG			equ WM_USER+5 	; wParam = color background
DP_HBITMAP			equ WM_USER+6 	; wParam = pBrush
;DP_MODELCOLOR			equ WM_USER+7 	; wParam = modelcolor
;DP_MODELTEXT			equ WM_USER+8 	; wParam = modeltext

STYLE_RED			equ 0001h
STYLE_GREEN			equ 0002h
STYLE_LIGHTB			equ 0003h

STYLE_TEXT			equ 0004h
STYLE_PERCENT			equ 0008h

STYLE_CENTER			equ 0010h


